name: Test

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: code clone
        uses: actions/checkout@v7
        
      - name: deploy via nginx
        run: cp index.html /var/www/html
        
      - name: deploy changes
        run: echo "deployment done"
